/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Before;
import org.junit.Test;
import org.springframework.test.web.servlet.MockMvc;

public class LibraryTest {

    private MockMvc mvc;
    @Test
    public void tesrHolle() throws Exception {
    }

    @Before
    public void setUp() throws Exception {


    }

    @Test public void testSomeLibraryMethod() {

    }
}
