/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class LibraryTest {
//    @Test
//    public void testSomeLibraryMethod() {
//
////        assertTrue("someLibraryMethod should return 'true'", shouldReturnTrue());
////        assertTrue("",firstThoughDoors());
//        CountCoins countCoins = new CountCoins();
//        countCoins.testCountCoins(5);
//
//        assertThat(5, is(5));
//    }
//
//    @Test
//    public void shouldCalculateChangeWaysGivenFiveCents() throws Exception {
//        CountCoins countCoins = new CountCoins();
//
//        Integer result = countCoins.testCountCoins(5);
//
//        assertThat(result, is(2));
//    }
//
//    public static boolean shouldReturnTrue() {
//        Doors100 classUnderTest = new Doors100();
//        boolean[] array = classUnderTest.creatDoors();
//        boolean returnBool = true;
//        for (boolean temp : array) {
//            if (temp) {
//                returnBool = false;
//            }
//        }
//        return returnBool;
//    }
//
//    public boolean firstThoughDoors() {
//        Doors100 classUnderTest = new Doors100();
//        boolean[] array = classUnderTest.creatDoors();
//        classUnderTest.changedArrayByNumber(1);
//
//        boolean returnBool = true;
//        for (boolean temp : classUnderTest.array) {
//            if (!temp) {
//                returnBool = false;
//            }
//        }
//        return returnBool;
//    }
}
