/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

        assertTrue("someLibraryMethod should return 'true'", shouldReturnTrue());
        assertTrue("",firstThoughDoors());
    }

    public static  boolean shouldReturnTrue(){
        Doors100 classUnderTest = new Doors100();
        boolean[] array =classUnderTest.creatDoors();
        boolean returnBool = true;
        for (boolean temp: array){
            if (temp){
                returnBool = false;
            }
        }
        return returnBool;
    }

    public   boolean firstThoughDoors() {
        Doors100 classUnderTest = new Doors100();
        boolean[] array =classUnderTest.creatDoors();
        classUnderTest.changedArrayByNumber(1);

        boolean returnBool = true;
        for (boolean temp: classUnderTest.array){
            if (!temp){
                returnBool = false;
            }
        }
        return returnBool;
    }
}
