/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String saySomething() {
        return "holle world,";
    }

    public  String otherString() {
        return  "I am hoggen";
    }



}
